items:
- uid: System.Environment.SpecialFolderOption
  id: Environment.SpecialFolderOption
  parent: System
  children:
  - System.Environment.SpecialFolderOption.Create
  - System.Environment.SpecialFolderOption.DoNotVerify
  - System.Environment.SpecialFolderOption.None
  href: System.Environment.SpecialFolderOption.yml
  name: Environment.SpecialFolderOption
  fullName: System.Environment.SpecialFolderOption
  type: Enum
  source:
    remote: &o0
      path: src/mscorlib/src/System/Environment.cs
      branch: master
      repo: https://github.com/chenkennt/coreclr.git
      key: 6c42ef8d
    path: src/mscorlib/src/System/Environment.cs
    startLine: 1544
  assemblies:
  - mscorlib
  namespace: System
  syntax:
    content: public enum SpecialFolderOption
    content.vb: Public Enum SpecialFolderOption
- uid: System.Environment.SpecialFolderOption.None
  id: None
  parent: System.Environment.SpecialFolderOption
  href: System.Environment.SpecialFolderOption.yml
  name: None
  fullName: System.Environment.SpecialFolderOption.None
  type: Field
  source:
    remote: *o0
    path: src/mscorlib/src/System/Environment.cs
    startLine: 1545
  assemblies:
  - mscorlib
  namespace: System
  syntax:
    content: None = 0
- uid: System.Environment.SpecialFolderOption.Create
  id: Create
  parent: System.Environment.SpecialFolderOption
  href: System.Environment.SpecialFolderOption.yml
  name: Create
  fullName: System.Environment.SpecialFolderOption.Create
  type: Field
  source:
    remote: *o0
    path: src/mscorlib/src/System/Environment.cs
    startLine: 1546
  assemblies:
  - mscorlib
  namespace: System
  syntax:
    content: Create = 32768
- uid: System.Environment.SpecialFolderOption.DoNotVerify
  id: DoNotVerify
  parent: System.Environment.SpecialFolderOption
  href: System.Environment.SpecialFolderOption.yml
  name: DoNotVerify
  fullName: System.Environment.SpecialFolderOption.DoNotVerify
  type: Field
  source:
    remote: *o0
    path: src/mscorlib/src/System/Environment.cs
    startLine: 1547
  assemblies:
  - mscorlib
  namespace: System
  syntax:
    content: DoNotVerify = 16384
references:
- uid: System
  isExternal: false
  name: System
  fullName: System
  type: Namespace
