items:
- uid: System.Diagnostics.Tracing.EventSourceSettings
  id: EventSourceSettings
  parent: System.Diagnostics.Tracing
  children:
  - System.Diagnostics.Tracing.EventSourceSettings.Default
  - System.Diagnostics.Tracing.EventSourceSettings.EtwManifestEventFormat
  - System.Diagnostics.Tracing.EventSourceSettings.EtwSelfDescribingEventFormat
  - System.Diagnostics.Tracing.EventSourceSettings.ThrowOnEventWriteErrors
  href: System.Diagnostics.Tracing.EventSourceSettings.yml
  name: EventSourceSettings
  fullName: System.Diagnostics.Tracing.EventSourceSettings
  type: Enum
  source:
    remote: &o0
      path: src/mscorlib/src/System/Diagnostics/Eventing/EventSource.cs
      branch: master
      repo: https://github.com/chenkennt/coreclr.git
      key: 6c42ef8d
    path: src/mscorlib/src/System/Diagnostics/Eventing/EventSource.cs
    startLine: 4016
  assemblies:
  - mscorlib
  namespace: System.Diagnostics.Tracing
  summary: Enables specifying event source configuration options to be used in the EventSource constructor.
  syntax:
    content: public enum EventSourceSettings
    content.vb: Public Enum EventSourceSettings
- uid: System.Diagnostics.Tracing.EventSourceSettings.Default
  id: Default
  parent: System.Diagnostics.Tracing.EventSourceSettings
  href: System.Diagnostics.Tracing.EventSourceSettings.yml
  name: Default
  fullName: System.Diagnostics.Tracing.EventSourceSettings.Default
  type: Field
  source:
    remote: *o0
    path: src/mscorlib/src/System/Diagnostics/Eventing/EventSource.cs
    startLine: 4022
  assemblies:
  - mscorlib
  namespace: System.Diagnostics.Tracing
  summary: This specifies none of the special configuration options should be enabled.
  syntax:
    content: Default = 0
- uid: System.Diagnostics.Tracing.EventSourceSettings.ThrowOnEventWriteErrors
  id: ThrowOnEventWriteErrors
  parent: System.Diagnostics.Tracing.EventSourceSettings
  href: System.Diagnostics.Tracing.EventSourceSettings.yml
  name: ThrowOnEventWriteErrors
  fullName: System.Diagnostics.Tracing.EventSourceSettings.ThrowOnEventWriteErrors
  type: Field
  source:
    remote: *o0
    path: src/mscorlib/src/System/Diagnostics/Eventing/EventSource.cs
    startLine: 4026
  assemblies:
  - mscorlib
  namespace: System.Diagnostics.Tracing
  summary: Normally an EventSource NEVER throws; setting this option will tell it to throw when it encounters errors.
  syntax:
    content: ThrowOnEventWriteErrors = 1
- uid: System.Diagnostics.Tracing.EventSourceSettings.EtwManifestEventFormat
  id: EtwManifestEventFormat
  parent: System.Diagnostics.Tracing.EventSourceSettings
  href: System.Diagnostics.Tracing.EventSourceSettings.yml
  name: EtwManifestEventFormat
  fullName: System.Diagnostics.Tracing.EventSourceSettings.EtwManifestEventFormat
  type: Field
  source:
    remote: *o0
    path: src/mscorlib/src/System/Diagnostics/Eventing/EventSource.cs
    startLine: 4033
  assemblies:
  - mscorlib
  namespace: System.Diagnostics.Tracing
  summary: >-
    Setting this option is a directive to the ETW listener should use manifest-based format when

    firing events. This is the default option when defining a type derived from EventSource

    (using the protected EventSource constructors).

    Only one of EtwManifestEventFormat or EtwSelfDescribingEventFormat should be specified
  syntax:
    content: EtwManifestEventFormat = 4
- uid: System.Diagnostics.Tracing.EventSourceSettings.EtwSelfDescribingEventFormat
  id: EtwSelfDescribingEventFormat
  parent: System.Diagnostics.Tracing.EventSourceSettings
  href: System.Diagnostics.Tracing.EventSourceSettings.yml
  name: EtwSelfDescribingEventFormat
  fullName: System.Diagnostics.Tracing.EventSourceSettings.EtwSelfDescribingEventFormat
  type: Field
  source:
    remote: *o0
    path: src/mscorlib/src/System/Diagnostics/Eventing/EventSource.cs
    startLine: 4040
  assemblies:
  - mscorlib
  namespace: System.Diagnostics.Tracing
  summary: >-
    Setting this option is a directive to the ETW listener should use self-describing event format

    when firing events. This is the default option when creating a new instance of the EventSource

    type (using the public EventSource constructors).

    Only one of EtwManifestEventFormat or EtwSelfDescribingEventFormat should be specified
  syntax:
    content: EtwSelfDescribingEventFormat = 8
references:
- uid: System.Diagnostics.Tracing
  isExternal: false
  name: System.Diagnostics.Tracing
  fullName: System.Diagnostics.Tracing
  type: Namespace
