items:
- uid: System.EnvironmentVariableTarget
  id: EnvironmentVariableTarget
  parent: System
  children:
  - System.EnvironmentVariableTarget.Machine
  - System.EnvironmentVariableTarget.Process
  - System.EnvironmentVariableTarget.User
  href: System.EnvironmentVariableTarget.yml
  name: EnvironmentVariableTarget
  fullName: System.EnvironmentVariableTarget
  type: Enum
  source:
    remote: &o0
      path: src/mscorlib/src/System/Environment.cs
      branch: master
      repo: https://github.com/chenkennt/coreclr.git
      key: 6c42ef8d
    path: src/mscorlib/src/System/Environment.cs
    startLine: 31
  assemblies:
  - mscorlib
  namespace: System
  syntax:
    content: public enum EnvironmentVariableTarget
    content.vb: Public Enum EnvironmentVariableTarget
- uid: System.EnvironmentVariableTarget.Process
  id: Process
  parent: System.EnvironmentVariableTarget
  href: System.EnvironmentVariableTarget.yml
  name: Process
  fullName: System.EnvironmentVariableTarget.Process
  type: Field
  source:
    remote: *o0
    path: src/mscorlib/src/System/Environment.cs
    startLine: 33
  assemblies:
  - mscorlib
  namespace: System
  syntax:
    content: Process = 0
- uid: System.EnvironmentVariableTarget.User
  id: User
  parent: System.EnvironmentVariableTarget
  href: System.EnvironmentVariableTarget.yml
  name: User
  fullName: System.EnvironmentVariableTarget.User
  type: Field
  source:
    remote: *o0
    path: src/mscorlib/src/System/Environment.cs
    startLine: 35
  assemblies:
  - mscorlib
  namespace: System
  syntax:
    content: User = 1
- uid: System.EnvironmentVariableTarget.Machine
  id: Machine
  parent: System.EnvironmentVariableTarget
  href: System.EnvironmentVariableTarget.yml
  name: Machine
  fullName: System.EnvironmentVariableTarget.Machine
  type: Field
  source:
    remote: *o0
    path: src/mscorlib/src/System/Environment.cs
    startLine: 36
  assemblies:
  - mscorlib
  namespace: System
  syntax:
    content: Machine = 2
references:
- uid: System
  isExternal: false
  name: System
  fullName: System
  type: Namespace
