items:
- uid: System.Xml.XmlWriterSettings
  id: XmlWriterSettings
  parent: System.Xml
  children:
  - System.Xml.XmlWriterSettings.#ctor
  - System.Xml.XmlWriterSettings.Async
  - System.Xml.XmlWriterSettings.CheckCharacters
  - System.Xml.XmlWriterSettings.Clone
  - System.Xml.XmlWriterSettings.CloseOutput
  - System.Xml.XmlWriterSettings.ConformanceLevel
  - System.Xml.XmlWriterSettings.Encoding
  - System.Xml.XmlWriterSettings.Indent
  - System.Xml.XmlWriterSettings.IndentChars
  - System.Xml.XmlWriterSettings.NamespaceHandling
  - System.Xml.XmlWriterSettings.NewLineChars
  - System.Xml.XmlWriterSettings.NewLineHandling
  - System.Xml.XmlWriterSettings.NewLineOnAttributes
  - System.Xml.XmlWriterSettings.OmitXmlDeclaration
  - System.Xml.XmlWriterSettings.Reset
  - System.Xml.XmlWriterSettings.WriteEndDocumentOnClose
  href: System.Xml.XmlWriterSettings.yml
  name: XmlWriterSettings
  fullName: System.Xml.XmlWriterSettings
  type: Class
  source:
    remote: &o0
      path: src/System.Xml.ReaderWriter/src/System/Xml/Core/XmlWriterSettings.cs
      branch: master
      repo: https://github.com/chenkennt/corefx.git
      key: 66d90a88
    path: src/System.Xml.ReaderWriter/src/System/Xml/Core/XmlWriterSettings.cs
    startLine: 30
  assemblies:
  - System.Xml.ReaderWriter
  namespace: System.Xml
  syntax:
    content: public sealed class XmlWriterSettings
    content.vb: Public NotInheritable Class XmlWriterSettings
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
- uid: System.Xml.XmlWriterSettings.#ctor
  id: '#ctor'
  parent: System.Xml.XmlWriterSettings
  href: System.Xml.XmlWriterSettings.yml
  name: XmlWriterSettings()
  fullName: System.Xml.XmlWriterSettings.XmlWriterSettings()
  type: Constructor
  source:
    remote: *o0
    path: src/System.Xml.ReaderWriter/src/System/Xml/Core/XmlWriterSettings.cs
    startLine: 66
  assemblies:
  - System.Xml.ReaderWriter
  namespace: System.Xml
  syntax:
    content: public XmlWriterSettings()
    content.vb: Public Sub New
- uid: System.Xml.XmlWriterSettings.Async
  id: Async
  parent: System.Xml.XmlWriterSettings
  href: System.Xml.XmlWriterSettings.yml
  name: Async
  fullName: System.Xml.XmlWriterSettings.Async
  type: Property
  source:
    remote: *o0
    path: src/System.Xml.ReaderWriter/src/System/Xml/Core/XmlWriterSettings.cs
    startLine: 75
  assemblies:
  - System.Xml.ReaderWriter
  namespace: System.Xml
  syntax:
    content: public bool Async { get; set; }
    content.vb: Public Property Async As Boolean
    parameters: []
    return:
      type: System.Boolean
- uid: System.Xml.XmlWriterSettings.Encoding
  id: Encoding
  parent: System.Xml.XmlWriterSettings
  href: System.Xml.XmlWriterSettings.yml
  name: Encoding
  fullName: System.Xml.XmlWriterSettings.Encoding
  type: Property
  source:
    remote: *o0
    path: src/System.Xml.ReaderWriter/src/System/Xml/Core/XmlWriterSettings.cs
    startLine: 89
  assemblies:
  - System.Xml.ReaderWriter
  namespace: System.Xml
  syntax:
    content: public Encoding Encoding { get; set; }
    content.vb: Public Property Encoding As Encoding
    parameters: []
    return:
      type: System.Text.Encoding
- uid: System.Xml.XmlWriterSettings.OmitXmlDeclaration
  id: OmitXmlDeclaration
  parent: System.Xml.XmlWriterSettings
  href: System.Xml.XmlWriterSettings.yml
  name: OmitXmlDeclaration
  fullName: System.Xml.XmlWriterSettings.OmitXmlDeclaration
  type: Property
  source:
    remote: *o0
    path: src/System.Xml.ReaderWriter/src/System/Xml/Core/XmlWriterSettings.cs
    startLine: 118
  assemblies:
  - System.Xml.ReaderWriter
  namespace: System.Xml
  syntax:
    content: public bool OmitXmlDeclaration { get; set; }
    content.vb: Public Property OmitXmlDeclaration As Boolean
    parameters: []
    return:
      type: System.Boolean
- uid: System.Xml.XmlWriterSettings.NewLineHandling
  id: NewLineHandling
  parent: System.Xml.XmlWriterSettings
  href: System.Xml.XmlWriterSettings.yml
  name: NewLineHandling
  fullName: System.Xml.XmlWriterSettings.NewLineHandling
  type: Property
  source:
    remote: *o0
    path: src/System.Xml.ReaderWriter/src/System/Xml/Core/XmlWriterSettings.cs
    startLine: 132
  assemblies:
  - System.Xml.ReaderWriter
  namespace: System.Xml
  syntax:
    content: public NewLineHandling NewLineHandling { get; set; }
    content.vb: Public Property NewLineHandling As NewLineHandling
    parameters: []
    return:
      type: System.Xml.NewLineHandling
- uid: System.Xml.XmlWriterSettings.NewLineChars
  id: NewLineChars
  parent: System.Xml.XmlWriterSettings
  href: System.Xml.XmlWriterSettings.yml
  name: NewLineChars
  fullName: System.Xml.XmlWriterSettings.NewLineChars
  type: Property
  source:
    remote: *o0
    path: src/System.Xml.ReaderWriter/src/System/Xml/Core/XmlWriterSettings.cs
    startLine: 151
  assemblies:
  - System.Xml.ReaderWriter
  namespace: System.Xml
  syntax:
    content: public string NewLineChars { get; set; }
    content.vb: Public Property NewLineChars As String
    parameters: []
    return:
      type: System.String
- uid: System.Xml.XmlWriterSettings.Indent
  id: Indent
  parent: System.Xml.XmlWriterSettings
  href: System.Xml.XmlWriterSettings.yml
  name: Indent
  fullName: System.Xml.XmlWriterSettings.Indent
  type: Property
  source:
    remote: *o0
    path: src/System.Xml.ReaderWriter/src/System/Xml/Core/XmlWriterSettings.cs
    startLine: 170
  assemblies:
  - System.Xml.ReaderWriter
  namespace: System.Xml
  syntax:
    content: public bool Indent { get; set; }
    content.vb: Public Property Indent As Boolean
    parameters: []
    return:
      type: System.Boolean
- uid: System.Xml.XmlWriterSettings.IndentChars
  id: IndentChars
  parent: System.Xml.XmlWriterSettings
  href: System.Xml.XmlWriterSettings.yml
  name: IndentChars
  fullName: System.Xml.XmlWriterSettings.IndentChars
  type: Property
  source:
    remote: *o0
    path: src/System.Xml.ReaderWriter/src/System/Xml/Core/XmlWriterSettings.cs
    startLine: 184
  assemblies:
  - System.Xml.ReaderWriter
  namespace: System.Xml
  syntax:
    content: public string IndentChars { get; set; }
    content.vb: Public Property IndentChars As String
    parameters: []
    return:
      type: System.String
- uid: System.Xml.XmlWriterSettings.NewLineOnAttributes
  id: NewLineOnAttributes
  parent: System.Xml.XmlWriterSettings
  href: System.Xml.XmlWriterSettings.yml
  name: NewLineOnAttributes
  fullName: System.Xml.XmlWriterSettings.NewLineOnAttributes
  type: Property
  source:
    remote: *o0
    path: src/System.Xml.ReaderWriter/src/System/Xml/Core/XmlWriterSettings.cs
    startLine: 203
  assemblies:
  - System.Xml.ReaderWriter
  namespace: System.Xml
  syntax:
    content: public bool NewLineOnAttributes { get; set; }
    content.vb: Public Property NewLineOnAttributes As Boolean
    parameters: []
    return:
      type: System.Boolean
- uid: System.Xml.XmlWriterSettings.CloseOutput
  id: CloseOutput
  parent: System.Xml.XmlWriterSettings
  href: System.Xml.XmlWriterSettings.yml
  name: CloseOutput
  fullName: System.Xml.XmlWriterSettings.CloseOutput
  type: Property
  source:
    remote: *o0
    path: src/System.Xml.ReaderWriter/src/System/Xml/Core/XmlWriterSettings.cs
    startLine: 217
  assemblies:
  - System.Xml.ReaderWriter
  namespace: System.Xml
  syntax:
    content: public bool CloseOutput { get; set; }
    content.vb: Public Property CloseOutput As Boolean
    parameters: []
    return:
      type: System.Boolean
- uid: System.Xml.XmlWriterSettings.ConformanceLevel
  id: ConformanceLevel
  parent: System.Xml.XmlWriterSettings
  href: System.Xml.XmlWriterSettings.yml
  name: ConformanceLevel
  fullName: System.Xml.XmlWriterSettings.ConformanceLevel
  type: Property
  source:
    remote: *o0
    path: src/System.Xml.ReaderWriter/src/System/Xml/Core/XmlWriterSettings.cs
    startLine: 233
  assemblies:
  - System.Xml.ReaderWriter
  namespace: System.Xml
  syntax:
    content: public ConformanceLevel ConformanceLevel { get; set; }
    content.vb: Public Property ConformanceLevel As ConformanceLevel
    parameters: []
    return:
      type: System.Xml.ConformanceLevel
- uid: System.Xml.XmlWriterSettings.CheckCharacters
  id: CheckCharacters
  parent: System.Xml.XmlWriterSettings
  href: System.Xml.XmlWriterSettings.yml
  name: CheckCharacters
  fullName: System.Xml.XmlWriterSettings.CheckCharacters
  type: Property
  source:
    remote: *o0
    path: src/System.Xml.ReaderWriter/src/System/Xml/Core/XmlWriterSettings.cs
    startLine: 252
  assemblies:
  - System.Xml.ReaderWriter
  namespace: System.Xml
  syntax:
    content: public bool CheckCharacters { get; set; }
    content.vb: Public Property CheckCharacters As Boolean
    parameters: []
    return:
      type: System.Boolean
- uid: System.Xml.XmlWriterSettings.NamespaceHandling
  id: NamespaceHandling
  parent: System.Xml.XmlWriterSettings
  href: System.Xml.XmlWriterSettings.yml
  name: NamespaceHandling
  fullName: System.Xml.XmlWriterSettings.NamespaceHandling
  type: Property
  source:
    remote: *o0
    path: src/System.Xml.ReaderWriter/src/System/Xml/Core/XmlWriterSettings.cs
    startLine: 266
  assemblies:
  - System.Xml.ReaderWriter
  namespace: System.Xml
  syntax:
    content: public NamespaceHandling NamespaceHandling { get; set; }
    content.vb: Public Property NamespaceHandling As NamespaceHandling
    parameters: []
    return:
      type: System.Xml.NamespaceHandling
- uid: System.Xml.XmlWriterSettings.WriteEndDocumentOnClose
  id: WriteEndDocumentOnClose
  parent: System.Xml.XmlWriterSettings
  href: System.Xml.XmlWriterSettings.yml
  name: WriteEndDocumentOnClose
  fullName: System.Xml.XmlWriterSettings.WriteEndDocumentOnClose
  type: Property
  source:
    remote: *o0
    path: src/System.Xml.ReaderWriter/src/System/Xml/Core/XmlWriterSettings.cs
    startLine: 284
  assemblies:
  - System.Xml.ReaderWriter
  namespace: System.Xml
  syntax:
    content: public bool WriteEndDocumentOnClose { get; set; }
    content.vb: Public Property WriteEndDocumentOnClose As Boolean
    parameters: []
    return:
      type: System.Boolean
- uid: System.Xml.XmlWriterSettings.Reset
  id: Reset
  parent: System.Xml.XmlWriterSettings
  href: System.Xml.XmlWriterSettings.yml
  name: Reset()
  fullName: System.Xml.XmlWriterSettings.Reset()
  type: Method
  source:
    remote: *o0
    path: src/System.Xml.ReaderWriter/src/System/Xml/Core/XmlWriterSettings.cs
    startLine: 301
  assemblies:
  - System.Xml.ReaderWriter
  namespace: System.Xml
  syntax:
    content: public void Reset()
    content.vb: Public Sub Reset
- uid: System.Xml.XmlWriterSettings.Clone
  id: Clone
  parent: System.Xml.XmlWriterSettings
  href: System.Xml.XmlWriterSettings.yml
  name: Clone()
  fullName: System.Xml.XmlWriterSettings.Clone()
  type: Method
  source:
    remote: *o0
    path: src/System.Xml.ReaderWriter/src/System/Xml/Core/XmlWriterSettings.cs
    startLine: 309
  assemblies:
  - System.Xml.ReaderWriter
  namespace: System.Xml
  syntax:
    content: public XmlWriterSettings Clone()
    content.vb: Public Function Clone As XmlWriterSettings
    return:
      type: System.Xml.XmlWriterSettings
references:
- uid: System.Xml
  isExternal: false
  name: System.Xml
  fullName: System.Xml
  type: Namespace
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  fullName: System.Object
- uid: System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
- uid: System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System
  isExternal: false
  name: System
  fullName: System
  type: Namespace
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  fullName: System.Boolean
- uid: System.Text.Encoding
  parent: System.Text
  isExternal: true
  name: Encoding
  fullName: System.Text.Encoding
- uid: System.Text
  isExternal: false
  name: System.Text
  fullName: System.Text
- uid: System.Xml.NewLineHandling
  parent: System.Xml
  isExternal: false
  href: System.Xml.NewLineHandling.yml
  name: NewLineHandling
  fullName: System.Xml.NewLineHandling
  type: Enum
- uid: System.String
  parent: System
  isExternal: true
  name: String
  fullName: System.String
- uid: System.Xml.ConformanceLevel
  parent: System.Xml
  isExternal: false
  href: System.Xml.ConformanceLevel.yml
  name: ConformanceLevel
  fullName: System.Xml.ConformanceLevel
  type: Enum
- uid: System.Xml.NamespaceHandling
  parent: System.Xml
  isExternal: false
  href: System.Xml.NamespaceHandling.yml
  name: NamespaceHandling
  fullName: System.Xml.NamespaceHandling
  type: Enum
- uid: System.Xml.XmlWriterSettings
  parent: System.Xml
  isExternal: false
  href: System.Xml.XmlWriterSettings.yml
  name: XmlWriterSettings
  fullName: System.Xml.XmlWriterSettings
  type: Class
