items:
- uid: System.Security
  id: System.Security
  children:
  - System.Security.SecureString
  - System.Security.SecureStringMarshal
  href: System.Security.yml
  name: System.Security
  fullName: System.Security
  type: Namespace
  source:
    remote:
      path: src/System.Security.SecureString/src/System/Security/SafeBSTRHandle.cs
      branch: master
      repo: https://github.com/chenkennt/corefx.git
      key: 66d90a88
    path: src/System.Security.SecureString/src/System/Security/SafeBSTRHandle.cs
    startLine: 6
  assemblies:
  - System.Security.SecureString
references:
- uid: System.Security.SecureString
  parent: System.Security
  isExternal: true
  name: SecureString
  fullName: System.Security.SecureString
- uid: System.Security.SecureStringMarshal
  isExternal: false
  href: System.Security.SecureStringMarshal.yml
  name: SecureStringMarshal
  fullName: System.Security.SecureStringMarshal
  type: Class
- uid: System.Security
  isExternal: false
  name: System.Security
  fullName: System.Security
