items:
- uid: System.Xml.XmlReaderSettings
  id: XmlReaderSettings
  parent: System.Xml
  children:
  - System.Xml.XmlReaderSettings.#ctor
  - System.Xml.XmlReaderSettings.Async
  - System.Xml.XmlReaderSettings.CheckCharacters
  - System.Xml.XmlReaderSettings.Clone
  - System.Xml.XmlReaderSettings.CloseInput
  - System.Xml.XmlReaderSettings.ConformanceLevel
  - System.Xml.XmlReaderSettings.DtdProcessing
  - System.Xml.XmlReaderSettings.IgnoreComments
  - System.Xml.XmlReaderSettings.IgnoreProcessingInstructions
  - System.Xml.XmlReaderSettings.IgnoreWhitespace
  - System.Xml.XmlReaderSettings.LineNumberOffset
  - System.Xml.XmlReaderSettings.LinePositionOffset
  - System.Xml.XmlReaderSettings.MaxCharactersFromEntities
  - System.Xml.XmlReaderSettings.MaxCharactersInDocument
  - System.Xml.XmlReaderSettings.NameTable
  - System.Xml.XmlReaderSettings.Reset
  href: System.Xml.XmlReaderSettings.yml
  name: XmlReaderSettings
  fullName: System.Xml.XmlReaderSettings
  type: Class
  source:
    remote: &o0
      path: src/System.Xml.ReaderWriter/src/System/Xml/Core/XmlReaderSettings.cs
      branch: master
      repo: https://github.com/chenkennt/corefx.git
      key: 66d90a88
    path: src/System.Xml.ReaderWriter/src/System/Xml/Core/XmlReaderSettings.cs
    startLine: 10
  assemblies:
  - System.Xml.ReaderWriter
  namespace: System.Xml
  syntax:
    content: public sealed class XmlReaderSettings
    content.vb: Public NotInheritable Class XmlReaderSettings
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
- uid: System.Xml.XmlReaderSettings.#ctor
  id: '#ctor'
  parent: System.Xml.XmlReaderSettings
  href: System.Xml.XmlReaderSettings.yml
  name: XmlReaderSettings()
  fullName: System.Xml.XmlReaderSettings.XmlReaderSettings()
  type: Constructor
  source:
    remote: *o0
    path: src/System.Xml.ReaderWriter/src/System/Xml/Core/XmlReaderSettings.cs
    startLine: 54
  assemblies:
  - System.Xml.ReaderWriter
  namespace: System.Xml
  syntax:
    content: public XmlReaderSettings()
    content.vb: Public Sub New
- uid: System.Xml.XmlReaderSettings.Async
  id: Async
  parent: System.Xml.XmlReaderSettings
  href: System.Xml.XmlReaderSettings.yml
  name: Async
  fullName: System.Xml.XmlReaderSettings.Async
  type: Property
  source:
    remote: *o0
    path: src/System.Xml.ReaderWriter/src/System/Xml/Core/XmlReaderSettings.cs
    startLine: 63
  assemblies:
  - System.Xml.ReaderWriter
  namespace: System.Xml
  syntax:
    content: public bool Async { get; set; }
    content.vb: Public Property Async As Boolean
    parameters: []
    return:
      type: System.Boolean
- uid: System.Xml.XmlReaderSettings.NameTable
  id: NameTable
  parent: System.Xml.XmlReaderSettings
  href: System.Xml.XmlReaderSettings.yml
  name: NameTable
  fullName: System.Xml.XmlReaderSettings.NameTable
  type: Property
  source:
    remote: *o0
    path: src/System.Xml.ReaderWriter/src/System/Xml/Core/XmlReaderSettings.cs
    startLine: 77
  assemblies:
  - System.Xml.ReaderWriter
  namespace: System.Xml
  syntax:
    content: public XmlNameTable NameTable { get; set; }
    content.vb: Public Property NameTable As XmlNameTable
    parameters: []
    return:
      type: System.Xml.XmlNameTable
- uid: System.Xml.XmlReaderSettings.LineNumberOffset
  id: LineNumberOffset
  parent: System.Xml.XmlReaderSettings
  href: System.Xml.XmlReaderSettings.yml
  name: LineNumberOffset
  fullName: System.Xml.XmlReaderSettings.LineNumberOffset
  type: Property
  source:
    remote: *o0
    path: src/System.Xml.ReaderWriter/src/System/Xml/Core/XmlReaderSettings.cs
    startLine: 98
  assemblies:
  - System.Xml.ReaderWriter
  namespace: System.Xml
  syntax:
    content: public int LineNumberOffset { get; set; }
    content.vb: Public Property LineNumberOffset As Integer
    parameters: []
    return:
      type: System.Int32
- uid: System.Xml.XmlReaderSettings.LinePositionOffset
  id: LinePositionOffset
  parent: System.Xml.XmlReaderSettings
  href: System.Xml.XmlReaderSettings.yml
  name: LinePositionOffset
  fullName: System.Xml.XmlReaderSettings.LinePositionOffset
  type: Property
  source:
    remote: *o0
    path: src/System.Xml.ReaderWriter/src/System/Xml/Core/XmlReaderSettings.cs
    startLine: 111
  assemblies:
  - System.Xml.ReaderWriter
  namespace: System.Xml
  syntax:
    content: public int LinePositionOffset { get; set; }
    content.vb: Public Property LinePositionOffset As Integer
    parameters: []
    return:
      type: System.Int32
- uid: System.Xml.XmlReaderSettings.ConformanceLevel
  id: ConformanceLevel
  parent: System.Xml.XmlReaderSettings
  href: System.Xml.XmlReaderSettings.yml
  name: ConformanceLevel
  fullName: System.Xml.XmlReaderSettings.ConformanceLevel
  type: Property
  source:
    remote: *o0
    path: src/System.Xml.ReaderWriter/src/System/Xml/Core/XmlReaderSettings.cs
    startLine: 125
  assemblies:
  - System.Xml.ReaderWriter
  namespace: System.Xml
  syntax:
    content: public ConformanceLevel ConformanceLevel { get; set; }
    content.vb: Public Property ConformanceLevel As ConformanceLevel
    parameters: []
    return:
      type: System.Xml.ConformanceLevel
- uid: System.Xml.XmlReaderSettings.CheckCharacters
  id: CheckCharacters
  parent: System.Xml.XmlReaderSettings
  href: System.Xml.XmlReaderSettings.yml
  name: CheckCharacters
  fullName: System.Xml.XmlReaderSettings.CheckCharacters
  type: Property
  source:
    remote: *o0
    path: src/System.Xml.ReaderWriter/src/System/Xml/Core/XmlReaderSettings.cs
    startLine: 143
  assemblies:
  - System.Xml.ReaderWriter
  namespace: System.Xml
  syntax:
    content: public bool CheckCharacters { get; set; }
    content.vb: Public Property CheckCharacters As Boolean
    parameters: []
    return:
      type: System.Boolean
- uid: System.Xml.XmlReaderSettings.MaxCharactersInDocument
  id: MaxCharactersInDocument
  parent: System.Xml.XmlReaderSettings
  href: System.Xml.XmlReaderSettings.yml
  name: MaxCharactersInDocument
  fullName: System.Xml.XmlReaderSettings.MaxCharactersInDocument
  type: Property
  source:
    remote: *o0
    path: src/System.Xml.ReaderWriter/src/System/Xml/Core/XmlReaderSettings.cs
    startLine: 156
  assemblies:
  - System.Xml.ReaderWriter
  namespace: System.Xml
  syntax:
    content: public long MaxCharactersInDocument { get; set; }
    content.vb: Public Property MaxCharactersInDocument As Long
    parameters: []
    return:
      type: System.Int64
- uid: System.Xml.XmlReaderSettings.MaxCharactersFromEntities
  id: MaxCharactersFromEntities
  parent: System.Xml.XmlReaderSettings
  href: System.Xml.XmlReaderSettings.yml
  name: MaxCharactersFromEntities
  fullName: System.Xml.XmlReaderSettings.MaxCharactersFromEntities
  type: Property
  source:
    remote: *o0
    path: src/System.Xml.ReaderWriter/src/System/Xml/Core/XmlReaderSettings.cs
    startLine: 173
  assemblies:
  - System.Xml.ReaderWriter
  namespace: System.Xml
  syntax:
    content: public long MaxCharactersFromEntities { get; set; }
    content.vb: Public Property MaxCharactersFromEntities As Long
    parameters: []
    return:
      type: System.Int64
- uid: System.Xml.XmlReaderSettings.IgnoreWhitespace
  id: IgnoreWhitespace
  parent: System.Xml.XmlReaderSettings
  href: System.Xml.XmlReaderSettings.yml
  name: IgnoreWhitespace
  fullName: System.Xml.XmlReaderSettings.IgnoreWhitespace
  type: Property
  source:
    remote: *o0
    path: src/System.Xml.ReaderWriter/src/System/Xml/Core/XmlReaderSettings.cs
    startLine: 191
  assemblies:
  - System.Xml.ReaderWriter
  namespace: System.Xml
  syntax:
    content: public bool IgnoreWhitespace { get; set; }
    content.vb: Public Property IgnoreWhitespace As Boolean
    parameters: []
    return:
      type: System.Boolean
- uid: System.Xml.XmlReaderSettings.IgnoreProcessingInstructions
  id: IgnoreProcessingInstructions
  parent: System.Xml.XmlReaderSettings
  href: System.Xml.XmlReaderSettings.yml
  name: IgnoreProcessingInstructions
  fullName: System.Xml.XmlReaderSettings.IgnoreProcessingInstructions
  type: Property
  source:
    remote: *o0
    path: src/System.Xml.ReaderWriter/src/System/Xml/Core/XmlReaderSettings.cs
    startLine: 204
  assemblies:
  - System.Xml.ReaderWriter
  namespace: System.Xml
  syntax:
    content: public bool IgnoreProcessingInstructions { get; set; }
    content.vb: Public Property IgnoreProcessingInstructions As Boolean
    parameters: []
    return:
      type: System.Boolean
- uid: System.Xml.XmlReaderSettings.IgnoreComments
  id: IgnoreComments
  parent: System.Xml.XmlReaderSettings
  href: System.Xml.XmlReaderSettings.yml
  name: IgnoreComments
  fullName: System.Xml.XmlReaderSettings.IgnoreComments
  type: Property
  source:
    remote: *o0
    path: src/System.Xml.ReaderWriter/src/System/Xml/Core/XmlReaderSettings.cs
    startLine: 217
  assemblies:
  - System.Xml.ReaderWriter
  namespace: System.Xml
  syntax:
    content: public bool IgnoreComments { get; set; }
    content.vb: Public Property IgnoreComments As Boolean
    parameters: []
    return:
      type: System.Boolean
- uid: System.Xml.XmlReaderSettings.DtdProcessing
  id: DtdProcessing
  parent: System.Xml.XmlReaderSettings
  href: System.Xml.XmlReaderSettings.yml
  name: DtdProcessing
  fullName: System.Xml.XmlReaderSettings.DtdProcessing
  type: Property
  source:
    remote: *o0
    path: src/System.Xml.ReaderWriter/src/System/Xml/Core/XmlReaderSettings.cs
    startLine: 231
  assemblies:
  - System.Xml.ReaderWriter
  namespace: System.Xml
  syntax:
    content: public DtdProcessing DtdProcessing { get; set; }
    content.vb: Public Property DtdProcessing As DtdProcessing
    parameters: []
    return:
      type: System.Xml.DtdProcessing
- uid: System.Xml.XmlReaderSettings.CloseInput
  id: CloseInput
  parent: System.Xml.XmlReaderSettings
  href: System.Xml.XmlReaderSettings.yml
  name: CloseInput
  fullName: System.Xml.XmlReaderSettings.CloseInput
  type: Property
  source:
    remote: *o0
    path: src/System.Xml.ReaderWriter/src/System/Xml/Core/XmlReaderSettings.cs
    startLine: 249
  assemblies:
  - System.Xml.ReaderWriter
  namespace: System.Xml
  syntax:
    content: public bool CloseInput { get; set; }
    content.vb: Public Property CloseInput As Boolean
    parameters: []
    return:
      type: System.Boolean
- uid: System.Xml.XmlReaderSettings.Reset
  id: Reset
  parent: System.Xml.XmlReaderSettings
  href: System.Xml.XmlReaderSettings.yml
  name: Reset()
  fullName: System.Xml.XmlReaderSettings.Reset()
  type: Method
  source:
    remote: *o0
    path: src/System.Xml.ReaderWriter/src/System/Xml/Core/XmlReaderSettings.cs
    startLine: 266
  assemblies:
  - System.Xml.ReaderWriter
  namespace: System.Xml
  syntax:
    content: public void Reset()
    content.vb: Public Sub Reset
- uid: System.Xml.XmlReaderSettings.Clone
  id: Clone
  parent: System.Xml.XmlReaderSettings
  href: System.Xml.XmlReaderSettings.yml
  name: Clone()
  fullName: System.Xml.XmlReaderSettings.Clone()
  type: Method
  source:
    remote: *o0
    path: src/System.Xml.ReaderWriter/src/System/Xml/Core/XmlReaderSettings.cs
    startLine: 272
  assemblies:
  - System.Xml.ReaderWriter
  namespace: System.Xml
  syntax:
    content: public XmlReaderSettings Clone()
    content.vb: Public Function Clone As XmlReaderSettings
    return:
      type: System.Xml.XmlReaderSettings
references:
- uid: System.Xml
  isExternal: false
  name: System.Xml
  fullName: System.Xml
  type: Namespace
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  fullName: System.Object
- uid: System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
- uid: System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System
  isExternal: false
  name: System
  fullName: System
  type: Namespace
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  fullName: System.Boolean
- uid: System.Xml.XmlNameTable
  parent: System.Xml
  isExternal: false
  href: System.Xml.XmlNameTable.yml
  name: XmlNameTable
  fullName: System.Xml.XmlNameTable
  type: Class
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  fullName: System.Int32
- uid: System.Xml.ConformanceLevel
  parent: System.Xml
  isExternal: false
  href: System.Xml.ConformanceLevel.yml
  name: ConformanceLevel
  fullName: System.Xml.ConformanceLevel
  type: Enum
- uid: System.Int64
  parent: System
  isExternal: true
  name: Int64
  fullName: System.Int64
- uid: System.Xml.DtdProcessing
  parent: System.Xml
  isExternal: false
  href: System.Xml.DtdProcessing.yml
  name: DtdProcessing
  fullName: System.Xml.DtdProcessing
  type: Enum
- uid: System.Xml.XmlReaderSettings
  parent: System.Xml
  isExternal: false
  href: System.Xml.XmlReaderSettings.yml
  name: XmlReaderSettings
  fullName: System.Xml.XmlReaderSettings
  type: Class
